---
raw:
  questions:
    glob: "*AssessmentExtract*.csv"
    columns:
      - Facility ID
      - Resident ID
      - Unit
      - Assessment ID
      - Assessment Type: category
      - question_key: category
      - item_value
      - Answer
    dates:
      - ARD: '%Y-%m-%d %H:%M:%S'
      - Answer_Date: '%Y-%m-%d %H:%M:%S'
    
  scoring:
    glob: "*AssessmentScoringExtract*.csv"
    columns: 
      - Facility ID
      - Resident ID
      - Unit
      - Assessment ID
      - RAI-MDS Status: category
      - Rug Group: category
      - CMI: Float32
      - CPS: Float32
      - DRS: Float32
      - COM: Float32
      - PAIN: Float32
      - CHESS: Float32
      - ISE: Float32
      - ADL_SHORT: Float32
      - ADL_LONG: Float32
      - ADL_HIER: Float32
      - ABS: Float32
      - PSI: Float32
      - PURS: Float32
      - FRS: Float32
    dates: 
      - ARD: '%Y-%m-%d %H:%M:%S'
      - Assessment Locked Date: '%Y-%m-%d %H:%M:%S'
      - Date Assessment Created: '%Y-%m-%d %H:%M:%S'
      - Date Assessment Revised: '%Y-%m-%d %H:%M:%S'

# concepts idk wip not used yet
# bronze:
#   questions:
#     columns:
#       - Facility ID
#       - Resident ID
#       - Unit
#       - Assessment ID
#       - Assessment Type: category
#       - question_key: category
#       - item_value
#       - Answer
#       - FILE_NAME: category
#       - INSTANCE: category
#       - PROVINCE: category
#     dates:
#       - ARD: '%Y-%m-%d %H:%M:%S'
#       - Answer_Date: '%Y-%m-%d %H:%M:%S'
#       - FILE_DATE: '%Y-%m-%d'
#       - INGESTION_TIMESTAMP: '%Y-%m-%d %H:%M:%S'
    
#   scoring:
#     columns: 
#       - Facility ID
#       - Resident ID
#       - Unit
#       - Assessment ID
#       - RAI-MDS Status: category
#       - Rug Group: category
#       - CMI: Float32
#       - CPS: Float32
#       - DRS: Float32
#       - COM: Float32
#       - PAIN: Float32
#       - CHESS: Float32
#       - ISE: Float32
#       - ADL_SHORT: Float32
#       - ADL_LONG: Float32
#       - ADL_HIER: Float32
#       - ABS: Float32
#       - PSI: Float32
#       - PURS: Float32
#       - FRS: Float32
#       - FILE_NAME: category
#       - INSTANCE: category
#       - PROVINCE: category
#     dates: 
#       - ARD: '%Y-%m-%d %H:%M:%S'
#       - Assessment Locked Date: '%Y-%m-%d %H:%M:%S'
#       - Date Assessment Created: '%Y-%m-%d %H:%M:%S'
#       - Date Assessment Revised: '%Y-%m-%d %H:%M:%S' 
#       - FILE_DATE: '%Y-%m-%d'
#       - INGESTION_TIMESTAMP: '%Y-%m-%d %H:%M:%S'


# silver_raw: 
#   questions:
#     columns:
#       - facility_id
#       - resident_id
#       - unit
#       - assessment_id 
#       - assessment_type: category
#       - question_key: category
#       - item_value
#       - answer
#       - FILE_NAME: category
#       - INSTANCE: category
#       - PROVINCE: category
#     dates:
#       - ard: '%Y-%m-%d %H:%M:%S'
#       - answer_date: '%Y-%m-%d %H:%M:%S'
#       - FILE_DATE: '%Y-%m-%d'
#       - INGESTION_TIMESTAMP: '%Y-%m-%d %H:%M:%S'
    
#   scoring:
#     columns:
#       - facility_id
#       - resident_id
#       - unit
#       - assessment_id 
#       - rai-mds_status: category
#       - rug_group: category
#       - cmi: Float32
#       - cps: Float32
#       - drs: Float32
#       - com: Float32
#       - pain: Float32
#       - chess: Float32
#       - ise: Float32
#       - adl_short: Float32
#       - adl_long: Float32
#       - adl_hier: Float32
#       - abs: Float32
#       - psi: Float32
#       - purs: Float32
#       - frs: Float32
#       - FILE_NAME: category
#       - INSTANCE: category
#       - PROVINCE: category
#     dates: 
#       - ard: '%Y-%m-%d %H:%M:%S'
#       - assessment_locked_date: '%Y-%m-%d %H:%M:%S'
#       - date_assessment_created: '%Y-%m-%d %H:%M:%S'
#       - date_assessment_revised: '%Y-%m-%d %H:%M:%S'
#       - FILE_DATE: '%Y-%m-%d'
#       - INGESTION_TIMESTAMP: '%Y-%m-%d %H:%M:%S'


# # <class 'pandas.core.frame.DataFrame'>
# # Index: 39813178 entries, 0 to 39813177
# # Data columns (total 22 columns):
# #  #   Column                Dtype         
# # ---  ------                -----         
# #  0   Facility ID           object        
# #  1   Resident ID           object        
# #  2   Unit                  object        
# #  3   Assessment ID         object        
# #  4   Assessment Type       category      
# #  5   Answer_Date           datetime64[ns]
# #  6   ARD                   datetime64[ns]
# #  7   question_key          object        
# #  8   item_value            object        
# #  9   Answer                object        
# #  10  filename              object        
# #  11  instance              object        
# #  12  file_date             datetime64[ns]
# #  13  ingestion_timestamp   datetime64[ns]
# #  14  Unique Assessment ID  object        
# #  15  Unique Resident ID    object        
# #  16  Facility Name         object        
# #  17  Province              object        
# #  18  Section               object        
# #  19  Question              object        
# #  20  Key:Question          object        
# #  21  _merge                category      
# # dtypes: category(2), datetime64[ns](4), object(16)
# # memory usage: 6.3+ GB








# # ---
# # common: 
# # # configurations shared across tables
# #   pandas: &common_pandas
# #       dtype: &common_dtype
# #         Facility ID: object
# #         Resident ID: object
# #         Unit: object
# #         Assessment ID: object
# #       dates: &common_dates
# #         ARD: '%Y-%m-%d %H:%M:%S'
# #       sep: '|'

# # questions:
# # # questions config
# #   glob: "*AssessmentExtract*.csv"
# #   pandas:
# #     <<: *common_pandas
# #     dtype:
# #       <<: *common_dtype
# #       Assessment Type: category
# #       question_key: category
# #       item_value: object
# #       Answer: object
# #     dates:
# #       <<: *common_dates
# #       Answer_Date: '%Y-%m-%d %H:%M:%S'

# # scoring:
# #   glob: "*AssessmentScoringExtract*.csv"
# #   pandas:
# #     <<: *common_pandas
# #     dtype:
# #       <<: *common_dtype
#       # RAI-MDS Status: category
#       # Rug Group: category
#       # CMI: Float32
#       # CPS: Float32
#       # DRS: Float32
#       # COM: Float32
#       # PAIN: Float32
#       # CHESS: Float32
#       # ISE: Float32
#       # ADL_SHORT: Float32
#       # ADL_LONG: Float32
#       # ADL_HIER: Float32
#       # ABS: Float32
#       # PSI: Float32
#       # PURS: Float32
#       # FRS: Float32
# #     dates: 
# #       <<: *common_dates
#       # Assessment Locked Date: '%Y-%m-%d %H:%M:%S'
#       # Date Assessment Created: '%Y-%m-%d %H:%M:%S'
#       # Date Assessment Revised: '%Y-%m-%d %H:%M:%S'

  

